modLoader = "javafml" #mandatory
loaderVersion = "[35,)" #mandatory
license = "MIT"
issueTrackerURL = "https://github.com/StrikerRockers-Mods/SBM-JukeBox/issues"
displayURL = "http://minecraft.curseforge.com/projects/sbm-jukebox"
authors = "StrikerRocker"

[[mods]] #mandatory
modId = "jukebox" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "[SBM] Jukebox" #mandatory
description = '''Simple mod that makes the jukebox inventory accessible''' #mandatory

[[dependencies.jukebox]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jukebox]]
modId = "minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"